# Read the Docs configuration file
# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

sphinx:
  fail_on_warning: true
  configuration: doc/source/conf.py

python:
  version: 3.8
  install:
    - requirements: doc/requirements.txt
